"""Write the repo's requirement files from the live machine (re-run after installs/updates; update-tools does it).

  requirements.txt       pip/uv-installable Python deps for refkit + nanobanana (CUDA torch index included)
  requirements-lock.txt  exact versions installed in the refkit venv (uv pip freeze)
  REQUIREMENTS.md        everything else: platform, runtimes, CLI tools (+ versions, install source), ComfyUI +
                         its torch, Blender, every model file (size, folder), Claude skills

Usage (system Python): python setup\\templates\\export-requirements.py [--repo <atelier clone>]
Lists come from setup\\lib.ps1 (single source of truth), versions are probed live.
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import platform
import re
import shutil
import subprocess
from pathlib import Path


def saved_env(name: str) -> str | None:
    """Process env first; else the user-level value saved in the registry (a terminal opened before it was set)."""
    if os.environ.get(name):
        return os.environ[name]
    if os.name == "nt":
        import winreg
        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as k:
                return winreg.QueryValueEx(k, name)[0]
        except OSError:
            return None
    return None

ap = argparse.ArgumentParser()
ap.add_argument("--repo", default=str(Path(__file__).resolve().parents[2]))
a = ap.parse_args()
REPO = Path(a.repo)
SETUP = REPO / "setup"
STUDIO_ROOT = Path(saved_env("ATELIER_ENGINE") or REPO / "engine")   # the engine folder
if not (STUDIO_ROOT / "ComfyUI").exists():
    # Never overwrite the manifest with an empty one because this shell doesn't see the engine.
    raise SystemExit(f"engine not found at {STUDIO_ROOT} (set ATELIER_ENGINE, or run setup\\09-local-ai.ps1 first)")
VENV_PY = STUDIO_ROOT / "venvs" / "refkit" / "Scripts" / "python.exe"
COMFY_PY = STUDIO_ROOT / "ComfyUI" / "python_embeded" / "python.exe"
ENV = {k: v for k, v in os.environ.items() if k != "PYTHONNOUSERSITE"}


def sh(*cmd: str, env: dict | None = None) -> str:
    exe = shutil.which(cmd[0]) or cmd[0]
    try:
        r = subprocess.run([exe, *cmd[1:]], capture_output=True, text=True, encoding="utf-8", errors="replace",
                           timeout=60, env=env or ENV)
        return (r.stdout or r.stderr).strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def first_version(text: str) -> str:
    m = re.search(r"\d+(?:\.\d+){1,3}(?:[-+.][\w.]+)?", text)
    return m.group(0) if m else (text.splitlines()[0][:40] if text else "not found")


def ps_list(name: str) -> list[str]:
    """Pull a `$Name = @(...)` string array out of lib.ps1."""
    text = (SETUP / "lib.ps1").read_text(encoding="utf-8")
    m = re.search(rf"\${name}\s*=\s*@\((.*?)\)\s*(?:#.*)?$", text, re.S | re.M)
    return re.findall(r"'([^']+)'", m.group(1)) if m else []


def ps_value(name: str) -> str:
    m = re.search(rf"\${name}\s*=\s*'([^']*)'", (SETUP / "lib.ps1").read_text(encoding="utf-8"))
    return m.group(1) if m else ""


# --- Python: requirements.txt + lock ---------------------------------------------------------------------
backend = ps_value("TorchBackend") or "cu130"
refkit_pkgs = ps_list("RefkitPackages")
freeze = sh(str(VENV_PY), "-m", "pip", "freeze") if VENV_PY.exists() else ""
if not freeze or "No module named pip" in freeze:
    freeze = sh("uv", "pip", "freeze", "--python", str(VENV_PY))
pins = {re.split(r"[=<>!~ ]", ln, maxsplit=1)[0].lower(): ln for ln in freeze.splitlines() if "==" in ln}


def pinned(pkg: str) -> str:
    base = re.split(r"[<>=!~\[ ]", pkg, maxsplit=1)[0].lower()
    have = pins.get(base, "")
    ver = have.split("==", 1)[1] if have else ""
    if any(c in pkg for c in "<>="):
        return pkg + (f"  # installed {ver}" if ver else "")
    return f"{pkg}>={ver.split('+')[0]}" if ver else pkg


torch_ver = pins.get("torch", "torch==?").split("==")[1]
tv_ver = pins.get("torchvision", "torchvision==?").split("==")[1]
req = [
    "# refkit venv (Python 3.12) + nanobanana.py. Generated by setup/templates/export-requirements.py - do not edit.",
    f"# Install: uv pip install --python <engine>\\venvs\\refkit\\Scripts\\python.exe --torch-backend {backend} -r requirements.txt",
    f"# (PyPI's Windows torch is CPU-only: the CUDA index below or --torch-backend {backend} is required.)",
    f"--extra-index-url https://download.pytorch.org/whl/{backend}",
    f"torch=={torch_ver}",
    f"torchvision=={tv_ver}",
    *[pinned(p) for p in refkit_pkgs],
    "",
]
(REPO / "requirements.txt").write_text("\n".join(req), encoding="utf-8")
(REPO / "requirements-lock.txt").write_text(
    "# Exact refkit venv state (uv pip freeze). Generated - do not edit.\n" + freeze.strip() + "\n", encoding="utf-8")

# --- tools ----------------------------------------------------------------------------------------------
TOOLS = [  # (command, version args, install source)
    ("python", ["--version"], "python.org / winget (3.12+)"), ("uv", ["--version"], "winget/astral"),
    ("node", ["--version"], "fnm (Node 24 LTS)"), ("git", ["--version"], "winget"), ("gh", ["--version"], "winget"),
    ("blender", ["--version"], "winget BlenderFoundation.Blender"), ("ffmpeg", ["-version"], "winget Gyan.FFmpeg"),
    ("magick", ["-version"], "winget ImageMagick"), ("exiftool", ["-ver"], "winget"), ("oxipng", ["--version"], "winget"),
    ("tesseract", ["--version"], "winget UB-Mannheim"), ("inkscape", ["--version"], "scoop extras"),
    ("potrace", ["--version"], "scoop"), ("vtracer", ["--version"], "release exe ~\\.local\\bin"),
    ("resvg", ["--version"], "scoop"), ("svgo", ["--version"], "npm -g"), ("pngquant", ["--version"], "scoop"),
    ("cwebp", ["-version"], "scoop libwebp"), ("avifenc", ["--version"], "scoop libavif"), ("f3d", ["--version"], "scoop extras"),
    ("gltf-transform", ["--version"], "npm -g @gltf-transform/cli"), ("gltfpack", ["-v"], "npm -g"),
    ("ktx", ["--version"], "scoop ktx-software"), ("rembg", ["--version"], "uv tool (py3.12)"),
    ("blender-mcp", ["--version"], "uv tool (Blender Lab)"), ("claude", ["--version"], "npm/official installer"),
]
tool_rows = []
for cmd, args, src in TOOLS:
    where = shutil.which(cmd) or shutil.which(cmd + ".cmd")
    ver = first_version(sh(where, *args)) if where else "MISSING"
    if cmd == "blender-mcp" and where:   # no --version flag; the pinned release lives in lib.ps1
        ver = ps_value("BlenderMcpVersion") or "installed"
    tool_rows.append(f"| `{cmd}` | {ver} | {src} |")

gpu = sh("nvidia-smi", "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader")
comfy_ver = sh("git", "-C", str(STUDIO_ROOT / "ComfyUI" / "ComfyUI"), "describe", "--tags")
comfy_torch = sh(str(COMFY_PY), "-s", "-c", "import torch,sys;print(torch.__version__, 'python', sys.version.split()[0])") \
    if COMFY_PY.exists() else "not installed"
comfy_pkgs = sh(str(COMFY_PY), "-s", "-m", "pip", "list", "--format=freeze") if COMFY_PY.exists() else ""
comfy_key = [ln for ln in comfy_pkgs.splitlines()
             if re.match(r"(torch|torchvision|torchaudio|comfy-|comfyui|transformers|spandrel|kornia)", ln, re.I)]

# --- models ---------------------------------------------------------------------------------------------
model_rows, total = [], 0
for f in sorted((STUDIO_ROOT / "models").rglob("*")):
    if f.suffix in (".safetensors", ".pth", ".gguf", ".ckpt", ".bin") and f.is_file():
        size = f.stat().st_size
        total += size
        model_rows.append(f"| `{f.parent.name}` | `{f.name}` | {size / 1e9:.2f} GB |")

skills = sorted(p.name for p in (REPO / "claude" / "skills").iterdir() if (p / "SKILL.md").exists())

md = f"""# Requirements

Generated {dt.date.today()} by `setup/templates/export-requirements.py` from the live machine - re-run it after
installing or updating anything (`python setup\\templates\\export-requirements.py`).

## Platform
- **Windows 11 + NVIDIA GPU only** as built ({platform.platform()}). GPU: {gpu or "n/a"}.
  The local models are int8/fp8 files with CUDA-only kernels (comfy-kitchen); Pixal3D/TRELLIS and SeedVR2 need
  CUDA. `nanobanana.py`, Blender, ffmpeg and the vector/QA tools are cross-platform; `setup/` is PowerShell + winget/scoop.
- Disk: models ~{total / 1e9:.0f} GB in `<engine>\\models`; ComfyUI portable + venvs ~15 GB. `<engine>` =
  `ATELIER_ENGINE` (default `<repo>\\engine`).
- Accounts/keys: `GEMINI_API_KEY` (user env var, paid Google calls). GitHub CLI login for the repo.

## Python
- `requirements.txt` - refkit venv + nanobanana deps (torch **{torch_ver}**, index **{backend}**).
- `requirements-lock.txt` - exact versions in `<engine>\\venvs\\refkit`.
- System Python 3.14 libs (docs skills, workflow exporter): {", ".join(f"`{p}`" for p in ps_list("PythonDocLibs"))}, `google-genai<3`.

## ComfyUI (engine)
- ComfyUI **{comfy_ver or "?"}** portable in `<engine>\\ComfyUI` - embedded torch {comfy_torch}.
- Launch flags (from `refkit bench`): see `setup/templates/comfy.cmd`. Model folders: `setup/templates/extra_model_paths.yaml`.
- Key packages in the embedded Python:
{chr(10).join(f"  - `{ln}`" for ln in comfy_key)}
- Core templates driven by refkit (models are downloaded from their embedded lists by `setup/09-local-ai.ps1`):
{chr(10).join(f"  - `{t}`" for t in ps_list("ComfyTemplates"))}

## CLI tools
| Tool | Version | Install source |
|---|---|---|
{chr(10).join(tool_rows)}

Also installed by `setup/` (winget): {", ".join(f"`{p}`" for p in ps_list("WingetPackages"))}.
Scoop (visual): {", ".join(f"`{p}`" for p in ps_list("VisualScoop"))}.

## Models (`<engine>\\models`, {len(model_rows)} files, {total / 1e9:.1f} GB)
| Folder | File | Size |
|---|---|---|
{chr(10).join(model_rows)}

## Claude Code
- Skills in `claude/skills/` (junctioned into `~\\.claude\\skills`): {", ".join(f"`{s}`" for s in skills)}.
- MCP: Blender MCP (`claude mcp add --scope user blender -- blender-mcp`).
"""
(REPO / "REQUIREMENTS.md").write_text(md, encoding="utf-8")
print(f"wrote requirements.txt ({len(req) - 5} deps), requirements-lock.txt ({len(pins)} pins), "
      f"REQUIREMENTS.md ({len(tool_rows)} tools, {len(model_rows)} models, {total / 1e9:.1f} GB)")
